project:
  type: website

website:
  title: "Liza's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/ds_project.qmd
        text: OECD Analysis
      - href: projects/shiny_app.qmd
        text: Shiny App

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
